baseURL = "https://www.dominic-ricottone.com/"
languageCode = "en-us"
title = "Dominic Ricottone"
disableKinds = ["taxonomy", "taxonomyTerm"]
summaryLength = 20

[permalinks]
posts = "/posts/:year/:month/:slug"

[markup.goldmark.renderer]
unsafe=true

