baseURL = "https://www.dominic-ricottone.com/"
locale = "en-US"
title = "Dominic Ricottone"
disableKinds = ["taxonomy"]
summaryLength = 20

[permalinks]
posts = "/posts/:year/:month/:slug"

[markup.goldmark.renderer]
unsafe=true

